### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by faktrol** [VityaSchel/session-id-generator#1]
Version for ubuntu to run on OS instead of browser?

**Comment by VityaSchel** [comment]
i'm web developer so no native versions will be published 
imo js with web workers is fast enough, 90% of code of this project's generator is simply calling sodium and 10% is if() calls and recursion

**Comment by VityaSchel** [comment]
I published CLI which is about 30% faster than browser
https://github.com/VityaSchel/session-id-generator/releases

**Comment by faktrol** [comment]
thx very much 👍
